package dev.mwalab.transaction

enum class TransactionInspectionStatus { PARSED, PARTIAL, UNSUPPORTED_VERSION, MALFORMED }

enum class TransactionInspectionLimitation {
    SIGNATURES_NOT_VERIFIED,
    BLOCKHASH_NOT_VALIDATED,
    HEADER_PRIVILEGES_ONLY,
    SEMANTIC_DECODING_NOT_IMPLEMENTED,
    LIMITED_PROGRAM_DECODING,
    VERSIONED_INSPECTION_PARTIAL,
    LOOKUP_ADDRESSES_UNRESOLVED,
    UNSUPPORTED_MESSAGE_VERSION,
}

enum class TransactionInspectionFailure {
    EMPTY_PAYLOAD, TRANSACTION_TOO_LARGE,
    TRUNCATED_SHORTVEC, NON_CANONICAL_SHORTVEC, SHORTVEC_OVERFLOW,
    SIGNATURE_COUNT_OUT_OF_RANGE, TRUNCATED_SIGNATURES, TRUNCATED_MESSAGE,
    TRUNCATED_HEADER, INVALID_HEADER, SIGNATURE_COUNT_MISMATCH,
    ACCOUNT_COUNT_OUT_OF_RANGE, TRUNCATED_ACCOUNTS, TRUNCATED_BLOCKHASH,
    INSTRUCTION_COUNT_OUT_OF_RANGE, TRUNCATED_INSTRUCTIONS,
    PROGRAM_INDEX_OUT_OF_RANGE, PROGRAM_IS_FEE_PAYER,
    INSTRUCTION_ACCOUNT_COUNT_OUT_OF_RANGE, TRUNCATED_INSTRUCTION_ACCOUNTS,
    ACCOUNT_INDEX_OUT_OF_RANGE, INSTRUCTION_DATA_TOO_LARGE, TRUNCATED_INSTRUCTION_DATA,
    LOOKUP_COUNT_OUT_OF_RANGE, TRUNCATED_LOOKUPS, EMPTY_ADDRESS_LOOKUP,
    LOOKUP_INDEX_COUNT_OUT_OF_RANGE, TOTAL_ACCOUNT_COUNT_OUT_OF_RANGE,
    TRAILING_DATA,
}

data class TransactionInspectionError(val reason: TransactionInspectionFailure, val byteOffset: Int) {
    init { require(byteOffset >= 0) { "Diagnostic offset must be nonnegative" } }
}
