package dev.mwalab.faults

/** Stable diagnostic IDs. UI copy is never used as event identity. */
enum class FaultId(val stableId: String) {
    NORMAL("NORMAL"),
    AUTH_REJECT("FAULT_AUTH_REJECT"),
    SIGN_REJECT("FAULT_SIGN_REJECT"),
    DELAY_5S("FAULT_DELAY_5S"),
    UNSUPPORTED_CHAIN("FAULT_UNSUPPORTED_CHAIN"),
    INVALID_PAYLOAD("FAULT_INVALID_PAYLOAD"),
    TOO_MANY_PAYLOADS("FAULT_TOO_MANY_PAYLOADS"),
    RPC_UNAVAILABLE("FAULT_RPC_UNAVAILABLE"),
    SUBMISSION_FAILURE("FAULT_SUBMISSION_FAILURE"),
    STALE_BLOCKHASH("FAULT_STALE_BLOCKHASH"),
}
